### ISSUE TITLE
Invalid License

### ISSUE THREAD

**Issue by joe-bell** [G3root/react-cva#3]
Hey @G3root!

[cva](https://github.com/joe-bell/cva/blob/main/LICENSE) uses Apache License 2.0 to preserve copyright in a permissive manner

Please can you make sure you follow the steps outlined in the license under section [“4. Redistribution”](https://github.com/joe-bell/cva/blob/main/LICENSE)?

Thank you 🙏🏼

**Comment by G3root** [comment]
> Hey @G3root!
> 
> [cva](https://github.com/joe-bell/cva/blob/main/LICENSE) uses Apache License 2.0 to preserve copyright in a permissive manner
> 
> Please can you make sure you follow the steps outlined in the license under section [“4. Redistribution”](https://github.com/joe-bell/cva/blob/main/LICENSE)?
> 
> Thank you 🙏🏼

thanks for this awesome library [cva](https://github.com/joe-bell/cva)

**Comment by joe-bell** [comment]
Thanks for resolving so quickly, I really appreciate it
